gitSourceBranch = "master"
changelog = true
classOrder = [
    "PathEZ",
    "Error",
]

apiCategories = [
    "Constructor",
    "Move Function",
]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/favicon.png"
