[package]
name = "untakeranonplay/pathez"
description = "Package for pathfinding in real time"
license = "MIT"
authors = ["Untaker_AnonPLAY <anonplay9@gmail.com>"]
version = "0.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = [
    "selene.toml",
    "aftman.toml",
    "moonwave.toml",
    "wally.toml",
    ".gitignore",
    ".moonwave",
    ".vscode",
    "build",
    "Tests",
    "SimplePath.lua",
    "README.md",
    "CHANGELOG.md",
    "LICENSE.md",
    "TestPlace.project.json",
]

[dependencies]
promise = "evaera/promise@^4.0"
signal = "sleitnick/signal@^1.5"